modelzoo/DLRM/train.py, modelzoo/WDL/train.py
Current perf of DLRM:
gstep/s:
tf 1.15.5 fp32: 72.48(baseline)
deeprec fp32: 93.0(1.28x)
deeprec bf16: 100.36(1.38x)
AUC:
tf 1.15.5 fp32: 0.76885
deeprec fp32: 0.77105
deeprec bf16: 0.77218
=> [Modelzoo] Improve DLRM's AUC in default setting.

tensorflow/core/common_runtime/gpu_tensorpool_allocator_test.cc
When parallel run multiple gpu unit-test, there's no enough
GPU memory for HugeMemoryAllocation in gpu_tensorpool_allocator_test.
=> [UT] Fix unit test failure of gpu_tensorpool_allocator_test.

docs/KafkaDataset.md, docs/index.md, tensorflow/core/kernels/data/kafka_dataset_op.cc, tensorflow/core/ops/dataset_ops.cc, tensorflow/python/data/ops/readers.py
Add KafkaGroupIODataset to support consumer rebalance.
=> [KafkaDataset] Add KafkaGroupIODataset to support consumer rebalance

cibuild/cpu-ut/cpu-core-ut.sh, cibuild/gpu-ut/gpu-core-ut.sh
Disable ev_allocator_tests by default. Once ev_allocate bug is fixed, enable the test again.
=> [CIBUILD] Disable ev_allocator_tests in cpu/gpu core ut.

tensorflow/core/api_def/base_api/api_def_FusedSafeEmbeddingLookupSparseLocal.pbtxt, tensorflow/core/api_def/base_api/api_def_FusedSafeEmbeddingLookupSparseLocalGrad.pbtxt, tensorflow/core/kernels/BUILD, tensorflow/core/kernels/fused_embedding/embedding_lookup_sparse_local_op.cc, tensorflow/core/kernels/fused_embedding/embedding_lookup_sparse_local_op_test.cc, tensorflow/core/kernels/fused_embedding/embedding_lookup_sparse_op.h, tensorflow/core/kernels/fused_embedding/embedding_lookup_sparse_post_grad_op_test.cc, tensorflow/core/kernels/fused_embedding/embedding_lookup_sparse_post_op.cc, tensorflow/core/kernels/fused_embedding/embedding_lookup_sparse_post_op_test.cc, tensorflow/core/kernels/fused_embedding/embedding_lookup_sparse_pre_op.cc, tensorflow/core/kernels/fused_embedding/embedding_lookup_sparse_pre_op_test.cc, tensorflow/core/ops/fused_embedding_ops.cc, tensorflow/python/ops/fused_embedding_ops.py
Verificate CPU embedding ops:
```bash
$ bazel test --flaky_test_attempts 1 --test_output=all --nocache_test_results --cxxopt=-D_GLIBCXX_USE_CXX11_ABI=0 //tensorflow/core/kernels:embedding_lookup_sparse_pre_op_test
$ bazel test --flaky_test_attempts 1 --test_output=all --nocache_test_results --cxxopt=-D_GLIBCXX_USE_CXX11_ABI=0 //tensorflow/core/kernels:embedding_lookup_sparse_post_op_test
$ bazel test --flaky_test_attempts 1 --test_output=all --nocache_test_results --cxxopt=-D_GLIBCXX_USE_CXX11_ABI=0 //tensorflow/core/kernels:embedding_lookup_sparse_post_grad_op_test
```
Currently, only integrated functionality code and accuracy is right, will increase its perf.
| ACC | WDL | WDL | DLRM | DLRM | Deep FM | Deep FM | DSSM  | DSSM |
| -- | -- | -- | -- | -- | -- | -- | -- | -- |
|  | value | …
=> [Embedding] Add CPU fused embedding ops.

tensorflow/core/kernels/segment_reduction_ops.cc, tensorflow/core/kernels/segment_reduction_ops_test.cc, tensorflow/python/kernel_tests/segment_reduction_ops_test.py
Parallelize UnsortedSegmentSum on CPU deivce.
Under the same condition,  we can see the “parallel” way is more effective.
Op | Row | Col | S_id | T_nums
-- | -- | -- | -- | --
UnsortedSegmentSum | 4096 | 1024 | 128 | 1
UnsortedSegmentSum | 4096 | 1024 | 128 | 2
UnsortedSegmentSum | 4096 | 1024 | 128 | 4
UnsortedSegmentSum | 4096 | 1024 | 128 | 8
UnsortedSegmentSum | 4096 | 1024 | 128 | 16
=> [Op] Parallelize UnsortedSegment op.

tensorflow/core/framework/embedding/cache.h, tensorflow/core/kernels/embedding_variable_ops_test.cc, tensorflow/core/kernels/kv_variable_ops.cc
This commit solves the following problems：
1. Improve LFUCache performance by eliminating calls to std::list::size().
2. Optimize the data structure of LFUCache.
3. Change the execution pattern of add_to_rank from multi-thread to single-thread. This modification can improve the E2E performance of 10% in our MMoE model test.
4. Add C++ UTs of caches.
=> [Embedding] Optimize the cache of multi-tier embedding storage.

tensorflow/core/kernels/kv_variable_ops.cc
Force pmem allocator to NORMAL layout to fix "Unsupport FreqCounter in subclass of ValuePtrBase" problem
=> [Allocator] Fix pmem allocator layout to NORMAL

tensorflow/core/kernels/BUILD, tensorflow/core/kernels/batched_non_max_suppression_op.cu.cc, tensorflow/core/kernels/bincount_op_gpu.cu.cc, tensorflow/core/kernels/dynamic_partition_op_gpu.cu.cc, tensorflow/core/kernels/fused_embedding/fused_embedding_post_ops_gpus.cu.cc, tensorflow/core/kernels/fused_embedding/fused_embedding_pre_ops_gpus.cu.cc, tensorflow/core/kernels/generate_box_proposals_op.cu.cc, tensorflow/core/kernels/histogram_op_gpu.cu.cc, tensorflow/core/kernels/non_max_suppression_op.cu.cc, tensorflow/core/kernels/reduction_gpu_kernels.cu.h, tensorflow/core/kernels/scan_ops_gpu.h, tensorflow/core/kernels/topk_op_gpu.h, tensorflow/core/kernels/where_op_gpu.cu.h, third_party/cub.BUILD, third_party/gpus/cuda/BUILD.tpl, third_party/gpus/cuda/BUILD.windows.tpl, third_party/gpus/cuda_configure.bzl
Use CUB from the CUDA Toolkit starting with version 11.0.
Backport of upstream commit c6769e20b.
=> [CUDA] Fix build failure with cuda11.6.

tensorflow/core/grappler/optimizers/BUILD, tensorflow/core/grappler/optimizers/concat_cast_fusing_test.cc
The FusedConcatCast kernel is available only for CPU, that's why the CI fails for GPU. I need to enable the test only for CPU.
=> [Grappler] Fix GPU Concat+Cast test issue.

serving/tools/timeline/timeline.py, tensorflow/core/common_runtime/executor.cc, tensorflow/core/common_runtime/step_stats_collector.cc, tensorflow/core/common_runtime/step_stats_collector.h, tensorflow/core/framework/step_stats.proto, tensorflow/core/kernels/data/captured_function.cc, tensorflow/core/platform/annotation.cc, tensorflow/core/platform/annotation.h, tensorflow/core/platform/default/device_tracer.cc, tensorflow/core/platform/posix/env.cc, tensorflow/core/profiler/internal/cpu/host_tracer.cc, tensorflow/core/profiler/internal/traceme_recorder.h, tensorflow/core/profiler/lib/BUILD, tensorflow/core/profiler/lib/traceme.cc, tensorflow/core/profiler/lib/traceme.h, tensorflow/python/client/timeline.py, tensorflow/python/training/basic_session_run_hooks.py
1. Fix unknown ops shown in the timeline
2. Add kernel launch event traces and correlations
3. enable calling context collections and corresponding attributions in the timeline events
4. Use uniformed thread id (begin from 1) for posix environments and enable the use_real_thread_id flag by default for more genuine timelines shown in google chrome tracing tools.
--------
- Many "unknown" ops and kernel executions without limited information.
- No launching events with latency metrics
- No Calling context attributions to seek which op launches the kernels or ops
- No invoke flows to indicate which op invokes a op or a kernel;
- Bad thread id attributions to see the real thread concurrencies;
I fix the `unknown` attributions in the timeline events, and introduce new `calling context` …
=> [Profiler] Support more information attributes for the built-in profiler traces

tensorflow/contrib/star/seastar/seastar_client_tag.cc, tensorflow/contrib/star/seastar/seastar_server_tag.cc
- when concurrent session.run,
out-of-order write on same fd may happen with concurrent multi user packets rpc requests
- with support for large user packet write by pollable_fd::write_some,
no need to split one rpc request into multi user packets
=> [Distributed] Remove user packet split to avoid multiple user packet out-of-order issue.

tensorflow/core/kernels/batch_matmul_op_impl.h
This results in a 20-50% improvement on some benchmarks, modest improvement on others and perf neutral for the rest.
=> [Op] Tune const kMaxCostOuterParallelism in BatchMatmul.

tensorflow/core/graph/mkl_layout_pass.cc, tensorflow/core/graph/mkl_layout_pass.h
Fix following issue occurred when compling.
```
ERROR: /whl_build/repo/ali_DeepRec/DeepRec/tensorflow/core/BUILD:3367:1: C++ compilation of rule '//tensorflow/core:core_cpu_impl' failed (Exit 1): gcc failed: error executing command
(cd /root/.cache/bazel/_bazel_root/31d1ea751fd7ccbf446ae91732fb258b/execroot/org_tensorflow && \
exec env - \
LD_LIBRARY_PATH=/home/pai/lib: \
PATH=/home/pai/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
PWD=/proc/self/cwd \
/usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections '-std=c++0x' -I/home/pai/include -I/root/.cache/bazel/_bazel_root/31d1ea751fd7ccbf446ae91732fb258b/external/local_co …
```
=> [Grappler] Fix the 'NodeIsInGpu is not declare' issue

serving/processor/serving/BUILD, serving/processor/storage/BUILD, tensorflow/BUILD
```shell
$ bazel build //serving/processor/serving:libserving_processor.so
...
ERROR: /home/marvin/workspace/DeepRec/serving/processor/serving/BUILD:25:1: in cc_binary rule //serving/processor/serving:libserving_processor.so: target '//tensorflow:libtensorflow_framework.so' is not visible from target '//serving/processor/serving:libserving_processor.so'. Check the visibility declaration of the former target if you think the dependency is legitimate
ERROR: /home/marvin/workspace/DeepRec/serving/processor/serving/BUILD:25:1: in cc_binary rule //serving/processor/serving:libserving_processor.so: target '//tensorflow:libtensorflow_framework.so.1' is not visible from target '//serving/processor/serving:libserving_processor.so'. Check the visibility declaration of the former target if you think …
```
=> [Serving] Fix serving_processor compile issue.

tensorflow/core/framework/embedding/cache.h
fix warning: 
`deleting object of abstract class type 'tensorflow::embedding::BatchCache<int>' which has non-virtual destructor will cause undefined behavior`
=> add virtual dtor to BatchCache

tensorflow/core/framework/embedding/multilevel_embedding.h
* fix compile for GCC12. Type of sc_.size is `std::vector<int64>`, not int64.
* `GertStorageSize()` is not used.
=> [Embedding] Remove useless code.

tensorflow/core/graph/graph_partition.h
fix warning: `tensorflow::GraphInfo` has a field `tensorflow::GraphInfo::output_types` whose type uses the anonymous namespace
=> [BUILD] Fix build warning caused by`tensorflow::GraphInfo` has a field `tensorflow::GraphInfo::output_types` whose type uses the anonymous namespace.

tensorflow/workspace.bzl
It's really microarchitecurally dependent, so take the value used by Linux.
=> [ARM] Define cacheline size for ARM in seastar.

tensorflow/core/framework/embedding/dram_leveldb_storage.h, tensorflow/core/framework/embedding/dram_pmem_storage.h, tensorflow/core/framework/embedding/dram_ssd_storage.h, tensorflow/core/framework/embedding/embedding_var.h, tensorflow/core/framework/embedding/hbm_dram_ssd_storage.h, tensorflow/core/framework/embedding/hbm_dram_storage.h, tensorflow/core/framework/embedding/lockless_hash_map_cpu.h, tensorflow/core/framework/embedding/single_tier_storage.h, tensorflow/core/framework/embedding/storage.h, tensorflow/core/framework/embedding/storage_manager.h, tensorflow/core/framework/embedding/value_ptr.h, tensorflow/core/kernels/kv_variable_ops.h, tensorflow/python/ops/embedding_variable_ops_test.py
Fix two bugs of HBM-DRAM storage:
1. Preventing from accessing uninitialized embeddings in asynchronous training.
2. Calling the Insert() interface when evict features causes data not to be updated.
=> [Embedding] Preventing from accessing uninitialized data and fixing the invalid eviction when use HBM-DRAM storage of EmbeddingVariable.

tensorflow/core/platform/BUILD, tensorflow/core/platform/default/logging.cc
In many environment, generating core files is not allowed, which makes it hard to find the root cause of fatal log messages. This patch print stack trace for fatal logs
=> [Debugability] Print stack trace for fatal logs

third_party/0001-Avoid-fetching-nullptr-when-use-featrue-filter.patch
The hang occurs when the last bucket that hash map tried to insert is occupied and others are set to deleted key.
=> [Embedding] Fix the hang when insert item into lockless hash map.

third_party/hwloc/hwloc_fix.patch
Fix hwloc build error. The reason is high version of GCC(>=10) with high version of linux kernel(>5.5).
=> [CIBUILD] Fix hwloc build error on alinux3.

tensorflow/core/framework/allocator.cc, tensorflow/core/framework/allocator.h, tensorflow/core/framework/allocator_registry.cc, tensorflow/core/framework/allocator_registry.h, tensorflow/core/framework/embedding/embedding_var.h, tensorflow/core/framework/ev_allocator.cc, tensorflow/core/framework/ev_allocator.h, tensorflow/core/framework/ev_allocator_gpu.cu.cc
stacked_dcn_v2模型
**单位：global_steps/sec**
| batch_size           | Default GPU Allocator  | GPU EVAllocator  | 加速比          |
| ----------------- | ---------------------- | ----------------- | ------------ |
| 512                        | 38.0088568                 | 39.0954629         | 1.02858823 |
| 8192                      | 12.0216879                  | 12.2838078          | 1.02180392  |
| batch_size           | Default GPU Allocator  | GPU EVAllocator  |
| ----------------- | ---------------------- | ----------------- |
| 512                        | 4993MiB                       | 5049MiB              |
| 8192                      | 17281MiB                      | 17337MiB          |
=> [Allocator] Implement GPU EVAllocator.

addons/triton/BUILD, addons/triton/tensorflow_backend_tf.cc, addons/triton/tensorflow_backend_tf.h, tensorflow/compiler/tests/depthwise_conv_op_test.py, tensorflow/compiler/xla/service/gpu/gpu_conv_algorithm_picker.cc, tensorflow/core/common_runtime/gpu/gpu_device.cc, tensorflow/core/kernels/fractional_avg_pool_op.cc, tensorflow/core/kernels/fractional_max_pool_op.cc, tensorflow/core/ops/nn_ops.cc, tensorflow/core/ops/nn_ops_test.cc, tensorflow/java/maven/proto/pom.xml, tensorflow/java/maven/tensorflow-hadoop/pom.xml, tensorflow/lite/kernels/gather_nd.cc, tensorflow/lite/kernels/gather_nd_test.cc, tensorflow/lite/kernels/internal/reference/reference_ops.h, tensorflow/python/kernel_tests/fractional_avg_pool_op_test.py, tensorflow/python/kernel_tests/fractional_max_pool_op_test.py, tensorflow/workspace.bzl, third_party/llvm/llvm.autogenerated.BUILD, third_party/png.BUILD
1. (TRITON) Add support for initialize operations
2. Boost sysmem carveout on Hopper to 4GB.
3. Fix overflow issue in default sysmem carveout.
4. Bump up tollerance in DepthwiseConv2DTest to avoid intermittent test failures.
5. Bump java hadoop and protobuf versions
6. Fix CVE-2022-35937
7. Add warmup pass in XLA auto tuning.
8. Increase default sysmem carveout on Pascal to 715MB
9. Fix "did not memcpy host-to-deice" errors in L0_resnet tests
10. (TRITON) Add support for loading libraries - TF1
11. Fix CVE-2022-41900
12. Bump zlib to 1.2.13.
13. Configure LLVM to use TF's zlib_archive.
=> [NV-TF] Sync commits with NV-TF2212

modelzoo/bst/train.py, modelzoo/dbmtl/train.py, modelzoo/dcn/train.py, modelzoo/dcnv2/train.py, modelzoo/deepfm/train.py, modelzoo/dien/train.py, modelzoo/din/train.py, modelzoo/dlrm/train.py, modelzoo/dssm/train.py, modelzoo/esmm/train.py, modelzoo/masknet/train.py, modelzoo/mlperf/train.py, modelzoo/mmoe/train.py, modelzoo/ple/train.py, modelzoo/simple_multitask/train.py, modelzoo/wide_and_deep/train.py
Disable GroupEmbedding and parquet_data with `--tf`, and fix a group_embedding issue in ESMM model.
=> [ModelZoo] Disable GroupEmbedding and parquet_data in stock tensorflow model.

docs/docs_en/Group-Embedding.md, docs/docs_zh/Group-Embedding.md, tensorflow/core/kernels/BUILD, tensorflow/core/kernels/group_lookup_backward.cu.cc, tensorflow/core/kernels/group_lookup_backward_base_ops.cu.h, tensorflow/core/kernels/group_lookup_forward.cu.cc, tensorflow/core/kernels/group_lookup_forward_base_ops.cu.h, tensorflow/core/ops/kv_variable_ops.cc, tensorflow/python/ops/embedding_ops.py, tensorflow/python/ops/group_embedding_lookup_ops.py
- Test performance based on DCNv2 increase from 13.4 step/s to 14.5 steps/s when batch_size is 8192.
=> [Embedding] Optimize cuda kernel implementation in GroupEmbedding.

.bazelrc, tensorflow/opensource_only.files, tensorflow/python/ops/array_ops.py, third_party/toolchains/java/BUILD
For workaround bazelbuild/bazel#8772 with Bazel >= 0.29.1 TensorFlow still targets Java 1.7 (See JAVACOPTS), which doesn't support "-parameters" flag. Starting from Java 11 (default since Bazel 0.29.1), a warning
message will be thrown if "-parameters" is passed. If "-Werror" also exists,
the compiling action will fail. To workaround this, we override the misc value of
the default java toolchain to remove "-parameters" flag.
=> [BUILD] Override default java toolchain to remove -parameters flag.

tensorflow/core/kernels/mkl_avgpooling_op.cc, tensorflow/core/kernels/mkl_batch_matmul_op.cc, tensorflow/core/kernels/mkl_concat_op.cc, tensorflow/core/kernels/mkl_conv_grad_filter_ops.cc, tensorflow/core/kernels/mkl_conv_grad_input_ops.cc, tensorflow/core/kernels/mkl_conv_ops.cc, tensorflow/core/kernels/mkl_fused_batch_norm_op.cc, tensorflow/core/kernels/mkl_lrn_op.cc, tensorflow/core/kernels/mkl_matmul_op_fused.cc, tensorflow/core/kernels/mkl_matmul_ops_common.h, tensorflow/core/kernels/mkl_maxpooling_op.cc, tensorflow/core/kernels/mkl_qmatmul_op.cc, tensorflow/core/kernels/mkl_quantize_op.cc, tensorflow/core/kernels/mkl_relu_op.cc, tensorflow/core/kernels/mkl_requantize_per_channel_op.cc, tensorflow/core/kernels/mkl_slice_op.cc, tensorflow/core/kernels/mkl_softmax_op.cc, tensorflow/core/kernels/mkl_transpose_op.cc, tensorflow/core/util/mkl_threadpool.h
Backport oneDNN-related commit from upstream. more detail information can be found at https://github.com/tensorflow/tensorflow/pull/59113
---
This PR contains the framework side implementation for a new oneDNN api relating to threadpool backend.
https://github.com/oneapi-src/oneDNN/blob/master/include/oneapi/dnnl/dnnl_threadpool.h#L69.
This api provides a method for the fwk to set the max_num_threads available to oneDNN at primitive creation time. oneDNN uses this as a hint to determine the decomposition of the kernel. Until now, the default value was assumed to be num_phys_cores_per_socket. This PR adjusts the assumption based on the actual num_threads. We see significant improvement to the conv_ops_benchmark_test when run on both sockets(~1.5x for some shapes). We also see in some …
=> [oneDNN] Implement setting max_num_threads hint to oneDNN at primitive creation time.

tensorflow/core/kernels/mkl_matmul_op.cc
Resolve the issue of '**ONEDNN_DEFAULT_FPMATH_MODE**' environment variable not working in oneDNN.
The feature introduction can be found at the link below:
https://oneapi-src.github.io/oneDNN/dev_guide_attributes_fpmath_mode.html#the-floating-point-math-mode-attribute
=> [oneDNN] Resolve the issue of 'ONEDNN_DEFAULT_FPMATH_MODE' environment variable not working.

tensorflow/core/framework/embedding/dram_leveldb_storage.h, tensorflow/core/framework/embedding/dram_pmem_storage.h, tensorflow/core/framework/embedding/dram_ssd_storage.h, tensorflow/core/framework/embedding/hbm_dram_ssd_storage.h, tensorflow/core/framework/embedding/hbm_dram_storage.h, tensorflow/core/framework/embedding/multi_tier_storage.h, tensorflow/core/framework/embedding/single_tier_storage.h, tensorflow/core/framework/embedding/ssd_hash_kv.h, tensorflow/core/framework/embedding/storage.h, tensorflow/core/framework/embedding/storage_factory.h, tensorflow/core/kernels/embedding_variable_ops_test.cc
1. The MultiTierStorage class no longer accesses the data of the KvInterface class
2. A subclass of MultiTierStorage consists of multiple SingleTierStorage objects, instead of KvInterface objects
=> [Embedding] Refactor the structure of MultiTierStorage class and its subclasses.

tensorflow/core/framework/embedding/embedding_var.h, tensorflow/core/framework/embedding/gpu_hash_map_kv.h, tensorflow/core/framework/embedding/gpu_hash_table.cu.cc, tensorflow/core/framework/embedding/gpu_hash_table.h, tensorflow/core/framework/embedding/kv_interface.h, tensorflow/core/framework/embedding/single_tier_storage.h, tensorflow/core/framework/embedding/storage.h, tensorflow/core/kernels/group_embedding/group_embedding_lookup_sparse_forward_ops.cu.cc, tensorflow/core/kernels/kv_variable_lookup_ops.cc, tensorflow/python/ops/embedding_variable_ops_gpu_test.py, third_party/cucollection.patch
Performance Comparison:
| Benchmark | batch_size | Global_steps |
| -------------- | ----- | ----- |
| DCNv2 train EV | 8192 | 11.5 |
| DCNv2 inference EV | 8192 | 12.6 |
| DCNv2 train EV | 2048 | 25.80 |
| DCNv2 inference EV | 2048 | 29.20 |
=> [Embedding] Support StaticGPUHashMap to optimize GPU EmbeddingVariable in inference.

tensorflow/core/common_runtime/executor.cc, tensorflow/core/framework/op_kernel.h
If there are lots of expensive ops that are ready at the same time, use multiple child threads of dispatch these ready ops. This is because dispatching ops on thread pool can be expensive
=> [Runtime] Dispatch expensive ops via multiple threads in theadpool.

cibuild/dockerfiles/Dockerfile.base-py3.6-cu114-ubuntu18.04, cibuild/dockerfiles/Dockerfile.base-py3.6-cu116-ubuntu18.04, cibuild/dockerfiles/Dockerfile.base-py3.8-cu117-ubuntu22.04, cibuild/dockerfiles/Dockerfile.base-py3.8-ubuntu20.04, cibuild/dockerfiles/Dockerfile.devel-py3.6-cu116-ubuntu18.04, cibuild/dockerfiles/Dockerfile.devel-py3.8-cu116-ubuntu20.04, cibuild/dockerfiles/Dockerfile.devel-py3.8-cu117-ubuntu22.04, cibuild/dockerfiles/Dockerfile.devel-py3.8-ubuntu20.04, cibuild/dockerfiles/Dockerfile.devel-py3.8-ubuntu22.04
There are some `&&` signs in the middle of package names in a single `pip install` command causing the single command interpreted as multiple commands by shell, and result in Dockerfile build failure.
This PR removes these `&&` signs.
=> [Dockerfile] Fix misuse of && in single pip install
