tensorflow/python/feature_column/feature_column_v2.py

This PR fixes API compatibility of embedding columns.

[Embedding] Fix API compatibility of embedding columns.

---

tensorflow/python/ops/embedding_ops.py

make sure Identity Op in API "embedding_lookup"

[Embedding] Fix: Graph is inconsistent in API ops.embedding_lookup().

---

tensorflow/core/protobuf/meta_graph.proto
tensorflow/python/framework/meta_graph.py
tensorflow/python/saved_model/builder_impl.py
tensorflow/python/tools/freeze_graph_test.py
tensorflow/python/training/incremental_saver.py
tensorflow/python/training/saver.py
tensorflow/tools/api/golden/v1/tensorflow.-meta-graph-def.pbtxt
tensorflow/tools/api/golden/v1/tensorflow.pbtxt
tensorflow/tools/api/golden/v1/tensorflow.saved_model.-builder.pbtxt
tensorflow/tools/api/golden/v1/tensorflow.saved_model.builder.-saved-model-builder.pbtxt
tensorflow/tools/api/golden/v1/tensorflow.train.pbtxt
tensorflow/tools/api/golden/v2/tensorflow.pbtxt

Add flag to control whether dump increment model to file.

[SavedModel] Add flag to control whether dump increment model to file.

---

tensorflow/python/training/saving/saveable_object_util.py

[Enhance]bazel build python2, fix cycle import

[BUILD] Support python2 build, fix cycle import issue.

---

tensorflow/core/common_runtime/direct_session.cc

Signed-off-by: Duyi-Wang <duyi.wang@intel.com>

[Allocator] Set threadpool of memory allocator in local DirectSession.

---

tensorflow/core/graph/template_logicsum_base.h
tensorflow/core/graph/template_select_base.h
tensorflow/python/kernel_tests/select_fusion_test.py

Support float32/int32/int64 type for select fusions

[Graph] Support float32/int32/int64 type for select fusions.

---

tensorflow/core/kernels/training_ops.cc
tensorflow/core/kernels/training_ops.h
tensorflow/core/kernels/training_ops_gpu.cu.cc
tensorflow/python/training/training_ops_test.py

[Op] Support SparseApplyAdagrad and SparseApplyFtrl on GPU.

---

tensorflow/core/graph/graph_constructor.cc

https://github.com/alibaba/DeepRec/issues/177

[SmartStage] Reserve enough variable related nodes. 

---

tensorflow/core/kernels/fused_embedding/embedding_lookup_sparse_post_op.cc

This PR fixes a gradient calculation error in the "embedding post_grad" op.

[Embedding] Fix the abnormal behavior in L2-norm calculation.

---

tensorflow/core/framework/experimental_pmem_allocator.cc
tensorflow/core/framework/experimental_pmem_allocator.h
tensorflow/core/framework/pmem_allocator.cc

Implement statistics in libpmem allocator, the implementation is similar to ev_allocator

[Allocator] Stats support for libpmem allocator

---

modelzoo/DIEN/README.md
modelzoo/DIEN/train.py
modelzoo/DIN/README.md
modelzoo/DIN/train.py
modelzoo/DLRM/README.md
modelzoo/DLRM/train.py
modelzoo/DeepFM/README.md
modelzoo/DeepFM/train.py
modelzoo/WDL/README.md
modelzoo/WDL/train.py

Signed-off-by: Duyi-Wang <duyi.wang@intel.com>

[Modelzoo] Update model default epochs setting.

---

modelzoo/DIEN/train.py
modelzoo/DIN/train.py
modelzoo/DLRM/train.py
modelzoo/DSSM/train.py
modelzoo/DeepFM/train.py
modelzoo/WDL/train.py

Signed-off-by: Duyi-Wang <duyi.wang@intel.com>

[Modelzoo] Change prefetch setting in data processing.

---

tests/model_benchmark/README.md
tests/model_benchmark/benchmark.sh
tests/model_benchmark/benchmark_result/checkpoint/README.md
tests/model_benchmark/benchmark_result/log/README.md
tests/model_benchmark/benchmark_result/record/script/README.md
tests/model_benchmark/benchmark_result/record/tool/check_model.sh
tests/model_benchmark/config.yaml
tests/model_benchmark/log_process.py

Co-authored-by: GosTraight2020 <shanlin.liu@intel.com>

[Tests] Add modelzoo benchmark scripts.

---

tests/model_benchmark/README.md
tests/model_benchmark/benchmark.sh
tests/model_benchmark/config.yaml

An option to define image type, let docker use gpu or not before running.

[Tests] Add GPU benchmark option.

---

tensorflow/core/kernels/unique_ali_op_util.h
tensorflow/tensorflow.bzl

gcc-8.3 compile deeprec will trigger compiler bug. Fixed issue: https://github.com/alibaba/DeepRec/issues/228

[BUILD] Fix compile error when use gcc-8.3.

---

cibuild/gpu-ut/gpu-contrib-ut.sh
tensorflow/core/kernels/training_ops_gpu.cu.cc

please choose 'rebase and merge'

[CIBUILD] Fix GPU contrib unit tests.

---

tests/model_benchmark/benchmark.sh
tests/model_benchmark/config.yaml
tests/model_benchmark/log_process.py

Signed-off-by: GosTraight2020 <shanlin.liu@intel.com>

[Tests] Add new models in benchmark scripts.

---

tensorflow/core/common_runtime/graph_execution_state.cc
tensorflow/core/common_runtime/graph_execution_state.h
tensorflow/core/graph/graph_constructor.cc
tensorflow/core/graph/graph_constructor.h
tensorflow/core/protobuf/config.proto

[SmartStage] Support for placing staged graph on CPU device in SmartStage.

---

modelzoo/features/EmbeddingVariable/WDL/train.py
modelzoo/features/pmem/benchmark.py
tensorflow/core/kernels/kv_variable_ops.cc

Set layout of pmem allocator to "normal_contiguous", replace storage_size from number to list

[Allocator] Fix pmem allocator layout config and benchmark script

---

cibuild/Dockerfile/Dockerfile.py3.6-cu114-ubuntu18.04
cibuild/Dockerfile/Dockerfile.py3.6-cu116-ubuntu18.04
tensorflow/contrib/learn/python/learn/learn_io/pandas_io.py

Upload Dockerfiles including cuda 11.4.2 and cuda 11.6.1.

[Dockerfile] Add Dockerfiles with cuda 11.4.2 and cuda 11.6.1.

---

serving/sdk/go/README.md
serving/sdk/go/demo.go
serving/sdk/go/processor.h
serving/sdk/java/README.md
serving/sdk/java/src/main/java/Demo.java
serving/sdk/python/README.md
serving/sdk/python/demo.py

[Serving] Support multiple languages.

---

tools/low_precision_optimize/README.md
tools/low_precision_optimize/calibrate.py
tools/low_precision_optimize/low_precision_optimize.py
tools/low_precision_optimize/simple_graph.py
tools/low_precision_optimize/tf_graph_transform_utils.py

Add low precision optimization tool.

[Quantization] Add low precision optimization tool.

---

tensorflow/core/common_runtime/device.cc
tensorflow/core/common_runtime/device.h
tensorflow/core/common_runtime/device_factory.cc
tensorflow/core/common_runtime/direct_session.cc
tensorflow/core/common_runtime/gpu/gpu_device.cc
tensorflow/core/common_runtime/gpu/gpu_device.h
tensorflow/core/common_runtime/gpu/gpu_device_factory.cc
tensorflow/core/common_runtime/gpu/gpu_id_utils.h
tensorflow/core/common_runtime/gpu/gpu_mem_allocator.h
tensorflow/core/common_runtime/gpu/gpu_process_state.cc
tensorflow/core/common_runtime/graph_execution_state.cc
tensorflow/core/framework/device_attributes.proto
tensorflow/core/framework/device_base.cc
tensorflow/core/framework/device_base.h
tensorflow/core/framework/resource_mgr.cc
tensorflow/core/framework/resource_mgr_test.cc
tensorflow/core/protobuf/config.proto
tensorflow/core/public/session.h
tensorflow/stream_executor/BUILD
tensorflow/stream_executor/cuda/cuda_driver.cc
tensorflow/stream_executor/cuda/cuda_platform.cc
tensorflow/stream_executor/cuda/cuda_platform.h
tensorflow/stream_executor/executor_cache.cc
tensorflow/stream_executor/executor_cache.h
tensorflow/stream_executor/platform.cc
tensorflow/stream_executor/platform.h

Now each session will be allocated a independent stream.
And the stream num equal to session num in the session_group.
All gpu devices(one stream per device) are sharing the same resoure.

[Runtime] Support gpu multi-streams in session_group.

---

serving/processor/serving/message_coding.cc
serving/processor/serving/message_coding.h
serving/processor/serving/model_impl.cc
serving/processor/serving/model_impl.h
serving/processor/serving/model_instance.cc
serving/processor/serving/model_instance.h
serving/processor/serving/model_message.h
serving/processor/serving/model_serving.cc
serving/processor/serving/util.cc
serving/processor/serving/util.h
serving/processor/tests/end2end/demo.cc

Request feed/fetch name must use signature's input/output key name.

[Serving] Normalize serving feed and fetch name.

---

tensorflow/c/BUILD
tensorflow/c/quantize_embedding_variable.cc
tensorflow/c/quantize_embedding_variable.h
tensorflow/python/BUILD
tensorflow/python/tensorflow.i
tensorflow/python/training/saving/saveable_object_util.py
tensorflow/python/util/quantize_embedding_variable.i
tensorflow/python/util/quantize_embedding_variable.py
tools/low_precision_optimize/README.md
tools/low_precision_optimize/low_precision_optimize.py
tools/low_precision_optimize/tf_graph_transform_utils.py

[Quantization] Add embedding variable quantization

[Quantization] Add embedding variable quantization.

---

tools/low_precision_optimize/low_precision_optimize.py

`shutil ` module can't handle files in HDFS correctly, and I can't run this tool for my models in HDFS, so I try to fix it.

[Quantization] Support HDFS files for low_precision_optimize.

---

serving/tools/timeline/timeline.py
tensorflow/core/distributed_runtime/worker_cache_logger.cc
tensorflow/python/client/timeline.py
tensorflow/python/client/timeline_test.py

[Profiler] Add detail information for RecvTensor.

---

tensorflow/core/BUILD
tensorflow/core/graph/mkl_layout_pass.cc
tensorflow/core/graph/mkl_layout_pass_lists.h
tensorflow/core/grappler/optimizers/remapper.cc

``` shell
// Add new item to rewrite list
$ TF_MKL_LAYOUT_PASS_GRAPH_REWRITE_LIST_ADD=MatMul,_FusedMatMul python train.py ...
// Remove specical item in rewrite list
$ TF_MKL_LAYOUT_PASS_GRAPH_REWRITE_LIST_REMOVE=MatMul,_FusedMatMul python train.py ...
Default list is from static gtl::FlatSet<string> FinalList().
```

[Grappler] Add macros to control the rewrite list in "mkl_layout_pass.cc"

---

tensorflow/workspace.bzl
third_party/0001-boringssl.patch

* fix wrong function declaration, fix build for GCC11&12

[BUILD] Fix boringssl compile error for GCC11 & GCC12.

---

cibuild/dockerfiles/Dockerfile.base-py3.6-cu112-ubuntu18.04
cibuild/dockerfiles/Dockerfile.base-py3.8-cu117-ubuntu22.04
cibuild/dockerfiles/Dockerfile.base-py3.8-ubuntu22.04
docs/DeepRec-Compile-And-Install.md
third_party/hwloc/hwloc_fix.patch
third_party/hwloc/workspace.bzl

[Dockerfile] Add docker images based ubuntu22.04 with cuda11.7.

---

tensorflow/core/api_def/base_api/api_def_QuantizedConv2DWithBiasReluAndSum.pbtxt
tensorflow/core/api_def/base_api/api_def_QuantizedConv2DWithBiasReluAndSumAndRequantize.pbtxt
tensorflow/core/framework/common_shape_fns.cc
tensorflow/core/framework/common_shape_fns.h
tensorflow/core/ops/mkl_nn_ops.cc
tensorflow/core/ops/nn_ops.cc

Add Operators definition at "nn_ops.cc&mkl_nn_ops.cc" to fix unkown op error.
``` shell
...
2022-06-21 10:03:02.483799: E tensorflow/core/framework/op_kernel.cc:1575] OpKernel ('op: "_MklQuantizedConv2DWithBiasReluAndSum" device_type: "CPU" constraint { name: "Tinput" allowed_values { list { type: DT_QINT8 } } } constraint { name: "Tfilter" allowed_values { list { type: DT_QINT8 } } } constraint { name: "out_type" allowed_values { list { type: DT_QINT32 } } } label: "QuantizedMklOp"') for unknown op: _MklQuantizedConv2DWithBiasReluAndSum
2022-06-21 10:03:02.483837: E tensorflow/core/framework/op_kernel.cc:1575] OpKernel ('op: "_MklQuantizedConv2DWithBiasReluAndSum" device_type: "CPU" constraint { name: "Tinput" allowed_values { list { type: DT_QUINT8 } } } constraint { name: "Tfilter" …
```

[Op] Add a list of Quantized* and _MklQuantized* ops.

---

tensorflow/python/ops/embedding_ops.py
tensorflow/python/training/async_embedding_stage.py

1. fix bug of tf.nn.embedding_lookup interface 
2. fix graph partition bug
3. place io subgraph and embedding lookup subgraph on cpu.

[Graph] Improve async embedding performance by placing IO and embedding lookup subgraph on cpu.

---

docs/Embedding-on-PMEM.md

[Docs] Update Embedding-on-PMEM.md.

---

addons/sparse_operation_kit/ReadMe.md

[SOK] Update ReadMe.md of SOK.

---

tensorflow/python/ops/kv_variable_ops.py

[Embedding] Compatible with older model when restoring EmbeddingVariable in init_from_proto.

---

WORKSPACE
tensorflow/core/framework/ev_allocator.cc
tensorflow/core/lib/hash/hash.cc
third_party/0001-Avoid-fetching-nullptr-when-use-featrue-filter.patch
third_party/arrow.patch
third_party/eigen3/eigen.patch

Fix some build failures on ARM

[ARM] Fix arm build failure.

---

tensorflow/core/lib/core/spin_lock.h
tensorflow/core/lib/core/spin_rw_lock.h

Implement c version of spinlock and read-write spinlock to fix build failure on ARM.

[ARM] Implement c version of spinlock to support multi-architectures

---

tensorflow/core/platform/BUILD
tensorflow/core/platform/default/logging.cc

[Debug] Print stack trace for fatal logs

---

tensorflow/core/kernels/BUILD
tensorflow/core/kernels/unique_ali_op.cc
tensorflow/core/kernels/unique_ali_op_gpu.cu.cc
tensorflow/core/kernels/unique_op_test.cc
tensorflow/python/kernel_tests/BUILD
tensorflow/python/kernel_tests/unique_op_test.py

Performance Comparison:
Benchmark				Time(ns)	Iterations
-------------------------------------------------------------------------------
BM_Unique_INT32_CPU/4096/1048576      85848    	1048576		190.8MB/s
BM_Unique_INT32_GPU/4096/1048576      68303		1048576		239.9MB/s

[Op] Implement GPU version of Unique OP.

---

tensorflow/core/framework/embedding/gpu_hash_map_kv.h

- conversion from int to size_t
- no return value

[Embedding] Fix EmbeddingVariable hang/coredump in GPU mode.

---

serving/configure.py

[BUILD] Fix processor compile issue with mkl_threadpool option.

---

tensorflow/core/BUILD
tensorflow/core/framework/embedding/embedding_var.h
tensorflow/core/graph/embedding_pass.cc
tensorflow/core/graph/graph.h
tensorflow/core/kernels/kv_variable_ops.cc
tensorflow/core/kernels/training_ali_op_helpers.h
tensorflow/core/kernels/training_ali_ops.cc
tensorflow/core/ops/kv_variable_ops.cc
tensorflow/core/ops/training_ali_ops.cc

- elimination duplicate in EmbeddingGather and EmbeddingApply ops

[Embedding] Add ForwardBackwardJointOptimizationPass.

---

addons/sparse_operation_kit/core/adapter/lookup_adapter.cpp
addons/sparse_operation_kit/core/adapter/lookup_adapter.hpp
tensorflow/cc/framework/cc_ops_test.cc
tensorflow/core/common_runtime/gpu/gpu_process_state.h
tensorflow/core/kernels/unique_ali_op_gpu.cu.cc

- Fix some code compatibility issue  imported by previous commit
- Implement the AliUniqueGPU Kernel as AsyncOpKernel to improve performance

[SOK & Op] Optimize SOK and Unique GPU Op.

---

WORKSPACE
docs/docs_en/Group-Embedding.md
docs/docs_en/index.md
docs/docs_zh/Group-Embedding.md
docs/docs_zh/index.md
modelzoo/features/group_embedding_lookup/dcnv2/README.md
modelzoo/features/group_embedding_lookup/dcnv2/data/README.md
modelzoo/features/group_embedding_lookup/dcnv2/result/README.md
modelzoo/features/group_embedding_lookup/dcnv2/train.py
modelzoo/features/group_embedding_lookup/script.sh
tensorflow/python/BUILD
tensorflow/python/feature_column/BUILD
tensorflow/python/feature_column/feature_column.py
tensorflow/python/feature_column/feature_column_v2.py
tensorflow/python/feature_column/feature_column_v2_test.py
tensorflow/python/feature_column/group_embedding_column.py
tensorflow/python/framework/config.py
tensorflow/python/framework/group_embedding_ops_utils.py
tensorflow/python/ops/embedding_ops.py
tensorflow/python/training/saving/saveable_object_util.py
third_party/HugeCTR.patch

Support tf.nn.group_embedding_lookup_sparse and group_embedding_sparse_scope API.
Performance: Dataset: Criteo-kaggle Model: DCNv2 batch_size: 512
--------------------------------------------------------------------
**1card**: 85 steps/s
**2card**: 122 steps/s
**4card**: 212 steps/s

[Embedding] Support group embedding to pack multiple feature columns's lookup/apply.

---

tensorflow/python/keras/BUILD
tensorflow/python/keras/layers/normalization.py
tensorflow/python/keras/layers/normalization_test.py

This reverts commit 65dabe124a99a2c76e826906bb2bc6cb49248cca.

Revert "Support fused batchnorm with any ndims and axis"

---

docs/docs_en/Group-Embedding.md
docs/docs_en/SOK.md
docs/docs_zh/Group-Embedding.md
docs/docs_zh/SOK.md
modelzoo/bst/train.py
modelzoo/dbmtl/train.py
modelzoo/dcn/train.py
modelzoo/dcnv2/train.py
modelzoo/deepfm/train.py
modelzoo/dlrm/train.py
modelzoo/dssm/train.py
modelzoo/esmm/train.py
modelzoo/features/group_embedding/dcnv2/train.py
modelzoo/masknet/train.py
modelzoo/mlperf/train.py
modelzoo/mmoe/train.py
modelzoo/ple/train.py
modelzoo/simple_multitask/train.py
modelzoo/wide_and_deep/train.py
tensorflow/python/feature_column/feature_column_v2.py
tensorflow/python/feature_column/group_embedding_column.py
tensorflow/python/framework/config.py
tensorflow/python/framework/group_embedding_ops_utils.py
tensorflow/python/ops/embedding_ops.py
tensorflow/python/ops/group_embedding_lookup_ops_test.py
tensorflow/tools/pip_package/BUILD

- Refine GroupEmbedding Implementation to ensure feature_column output order is sequential consistent with native API

[Embedding] Refine GroupEmbedding Implementation and introduction docs

---

tensorflow/core/kernels/kv_variable_ops.h
tensorflow/python/ops/embedding_variable_ops_test.py

[Embedding] Support restore custom dimension of Embedding Variable.

[Embedding] Support restore custom dimension of Embedding Variable.

---

cibuild/dockerfiles/Dockerfile.base-py3.8-ubuntu22.04-arm64
cibuild/dockerfiles/Dockerfile.devel-py3.8-ubuntu22.04-arm64

Add Dockerfile for base and devel image on ARM platforms.

[Dockerfile] Add docker images for ARM based on ubuntu22.04.

---

cibuild/dockerfiles/Dockerfile.devel-py3.8-ubuntu22.04-arm64

1. Removal of modified apt sources.
2. Update the base image link.

[CIBUILD] Upgrade  arm cpu devel dockerfile.

---

tensorflow/core/common_runtime/optimization_registry.h

XLA optimization pass can be disabled by setting environment variable `TF_DISABLE_XLA=1`.

[XLA] Add switch for XLA optimization pass.

---

tensorflow/core/kernels/tensor_buffer_ops.cc

Tested by models in modelzoo: avg global_step improve 0.6 steps/s

[Op] Optimize TensorBufferPutGpuOp which is used in smart_stage.

---

tensorflow/python/feature_column/feature_column.py
tensorflow/python/feature_column/feature_column_v2.py
tensorflow/python/feature_column/feature_column_v2_test.py
tensorflow/python/graph_optimizer/sample_awared_graph_compression.py
tensorflow/python/ops/embedding_variable_ops_test.py

…e_column.categorical_column_with_embedding`.

[Embedding] Support dtype `tf.int32` using feature_column API `tf.feature_column.categorical_column_with_embedding`.

---

tensorflow/core/kernels/BUILD
tensorflow/core/kernels/segment_reduction_ops.cc
tensorflow/core/kernels/segment_reduction_ops.h
tensorflow/core/kernels/segment_reduction_ops_benchmark_test.cc
tensorflow/core/kernels/segment_reduction_ops_gpu.cu.cc
tensorflow/core/kernels/segment_reduction_ops_gpu.cu.h
tensorflow/core/kernels/segment_reduction_ops_util.cc
tensorflow/core/kernels/segment_reduction_ops_util.h
tensorflow/core/util/gpu_device_functions.h

Including Ops: SegmentSum, SegmentMean, SegmentProd, SegmentMin, SegmentMax.
Performance:
SegmentSum Benchmark          Time(ns) Iterations
-------------------------------------------------
BM_SegmentSum_cpu_4096_16        32226      21750
BM_SegmentSum_cpu_8192_16        55985      10000
BM_SegmentSum_cpu_16384_16      107111       6357
BM_SegmentSum_gpu_4096_16        32131      21987
BM_SegmentSum_gpu_8192_16        32011      22761
BM_SegmentSum_gpu_16384_16       30302      23078
SegmentMean Benchmark         Time(ns) Iterations
-------------------------------------------------
BM_SegmentMean_cpu_4096_16       34624      20100
BM_SegmentMean_cpu_8192_16       60662      10000
BM_SegmentMean_cpu_16384_16     115611       6019
BM_SegmentMean_gpu_4096_16       43480      16093 …

[Op] Optimize list of SegmentReductionOps.

---

tensorflow/core/kernels/BUILD
tensorflow/core/kernels/segment_reduction_ops.cc
tensorflow/core/kernels/segment_reduction_ops.h
tensorflow/core/kernels/segment_reduction_ops_benchmark_test.cc
tensorflow/core/kernels/segment_reduction_ops_gpu.cu.cc
tensorflow/core/kernels/segment_reduction_ops_gpu.cu.h
tensorflow/core/kernels/segment_reduction_ops_util.cc
tensorflow/core/kernels/segment_reduction_ops_util.h
tensorflow/core/util/gpu_device_functions.h

Including Ops: SegmentSum, SegmentMean, SegmentProd, SegmentMin, SegmentMax.
Performance:
SegmentSum Benchmark          Time(ns) Iterations
-------------------------------------------------
BM_SegmentSum_cpu_4096_16        32226      21750
BM_SegmentSum_cpu_8192_16        55985      10000
BM_SegmentSum_cpu_16384_16      107111       6357
BM_SegmentSum_gpu_4096_16        32131      21987
BM_SegmentSum_gpu_8192_16        32011      22761
BM_SegmentSum_gpu_16384_16       30302      23078
SegmentMean Benchmark         Time(ns) Iterations
-------------------------------------------------
BM_SegmentMean_cpu_4096_16       34624      20100
BM_SegmentMean_cpu_8192_16       60662      10000
BM_SegmentMean_cpu_16384_16     115611       6019
BM_SegmentMean_gpu_4096_16       43480      16093 …

[Op] Optimize list of GPU SegmentReductionOps. 

---

COMMITTERS.md
addons/sparse_operation_kit/legacy/ReadMe.md
docs/docs_en/Estimator-Compile-And-Install.md
docs/docs_en/Incremental-Checkpoint.md
docs/docs_en/Sample-awared-Graph-Compression.md
docs/docs_en/SessionGroup.md
docs/docs_en/TFServing-Compile-And-Install.md
docs/docs_zh/Estimator-Compile-And-Install.md
docs/docs_zh/Incremental-Checkpoint.md
docs/docs_zh/Sample-awared-Graph-Compression.md
docs/docs_zh/SessionGroup.md
docs/docs_zh/TFServing-Compile-And-Install.md
tensorflow/workspace.bzl

1. Update seastar URL
2. Update user docs.

[Docs] Transfer serving, estimator, seastar to new organization.

---

tensorflow/stream_executor/cuda/cuda_12_0.inc
tensorflow/stream_executor/cuda/cuda_driver.cc
tensorflow/stream_executor/cuda/cuda_runtime_12_0.inc
tensorflow/stream_executor/cuda/cuda_stub.cc
tensorflow/stream_executor/cuda/cudart_stub.cc
tensorflow/stream_executor/cuda/cusparse_12_0.inc
tensorflow/stream_executor/cuda/cusparse_stub.cc
tensorflow/stream_executor/platform/default/dso_loader.cc
third_party/gpus/cuda/cuda_config.h.tpl
third_party/gpus/cuda_configure.bzl

Cherry-pick list of commit from NV-TF to support CUDA12.0.
896283a6100cd1d654c94df466a59d66c67b3758
c13649af920884b96202b82f909294ee4704551b
8a04c11d0538e18b02c7b29d7fca4f1756a36cff
a2926754c43aea599f017d3479dcfc2978d89eea
a508a05dae5a2c4ddda1f46f413430ec36abde31
57c3bfd44ce8935a91d5ad750a01bcd62191bb35
8fc3bafff5159b7402f3a0a01ff13c48db186183

[CUDA] Support CUDA 12.

---

modelzoo/masknet/train.py

1. Use layernorm instead of batchnorm for easier understanding.
2. Refine variable name and error message to align with paper.

[Modelzoo] Update masknet example with layernorm. (#810)

---

tensorflow/core/graph/mkl_layout_pass_test.cc
tensorflow/core/grappler/optimizers/remapper.cc
tensorflow/core/grappler/optimizers/remapper_test.cc
tensorflow/core/kernels/mkl_fused_ops_test.cc
tensorflow/core/kernels/mkl_matmul_op_fused.cc
tensorflow/core/kernels/mkl_matmul_ops_common.h
tensorflow/core/ops/math_ops.cc
tensorflow/core/ops/mkl_nn_ops.cc

[Grappler] Enable MKL Matmul + Bias + LeakyRelu fusion.

---

tensorflow/core/kernels/kv_variable_save_restore_ops.cc

'invalid resource handle' throw when calling KvResourceImportV3 and enable MPS .

[Embedding] Resolve cuda resource issue in KvResourceImportV3 kernel.

---

tensorflow/core/common_runtime/gpu/gpu_device_placement_pass.cc

Ignore the control edge of const op, because the
control edge does not require data transfer.

[Graph] Fix the control edge connection bug for device placement optimization.

---

tensorflow/core/framework/embedding/dram_leveldb_storage.h
tensorflow/core/framework/embedding/dram_pmem_storage.h
tensorflow/core/framework/embedding/dram_ssd_storage.h
tensorflow/core/framework/embedding/embedding_var.h
tensorflow/core/framework/embedding/globalstep_shrink_policy.h
tensorflow/core/framework/embedding/hbm_dram_ssd_storage.h
tensorflow/core/framework/embedding/hbm_dram_storage.h
tensorflow/core/framework/embedding/l2weight_shrink_policy.h
tensorflow/core/framework/embedding/shrink_policy.h
tensorflow/core/framework/embedding/single_tier_storage.h
tensorflow/core/framework/embedding/storage.h
tensorflow/core/kernels/embedding_variable_ops_test.cc
tensorflow/core/kernels/save_restore_v2_ops.cc
tensorflow/python/ops/embedding_variable_ops_test.py

1. Move ShrinkPolicy from Storage class to EmbeddingVar class.
2. Refactor the structure of ShrinkPolicy.

[Embedding] Add ShrinkArgs to refactor shrink functions in Embedding.

---

modelzoo/bst/train.py
modelzoo/dcn/train.py
modelzoo/dcnv2/train.py
modelzoo/deepfm/train.py
modelzoo/din/train.py
modelzoo/dlrm/train.py
modelzoo/dssm/train.py
modelzoo/esmm/train.py
modelzoo/features/group_embedding/dcnv2/train.py
modelzoo/masknet/train.py
modelzoo/mlperf/train.py
modelzoo/mmoe/train.py
modelzoo/ple/train.py
modelzoo/simple_multitask/train.py
modelzoo/wide_and_deep/train.py

Fix embedding_dim setting error that would cause segmentation fault in SOK at the same time.

[ModelZoo] Fix hung issue when using both SOK and SmartStaged simultaneously.

---

tensorflow/cc/BUILD
tensorflow/core/BUILD
tensorflow/core/graph/smart_stage_pass.cc
tensorflow/core/protobuf/config.proto
tensorflow/python/training/smart_stage_options.py
tensorflow/python/training/training.py

searching.
Support IteratorGetNext node as the starting node for searching
the boundary of stage subgraph.

[Graph] Support IteratorGetNext for SmartStage as a starting node for

---

modelzoo/bst/README.md
modelzoo/dbmtl/README.md
modelzoo/dcn/README.md
modelzoo/deepfm/README.md
modelzoo/dien/README.md
modelzoo/din/README.md
modelzoo/dlrm/README.md
modelzoo/dssm/README.md
modelzoo/esmm/README.md
modelzoo/mmoe/README.md
modelzoo/ple/README.md
modelzoo/simple_multitask/README.md
modelzoo/wide_and_deep/README.md

Models: bst/dbmtl/dcn/deepfm/dien/din/dlrm/dssm/esmm/mmoe/ple/simple_multitask/wide_and_deep

[ModelZoo] Update modelzoo README.

---

tensorflow/tools/pip_package/build_sok.sh
tensorflow/workspace.bzl

related commit in HugeCTR: https://github.com/NVIDIA-Merlin/HugeCTR/commit/e4575539d7edc00f3330cf2c1278c7baeb9546a5

[Distributed] Fix wgrad bug in Sparse Operation Kit.

---

tensorflow/python/training/async_embedding_stage.py
tensorflow/python/training/monitored_session.py

[Graph] Fix hang bug for async embedding lookup.

---

tensorflow/core/common_runtime/executor.cc

The original code assumes the last 4 bits of the CPU cycle count is uniformly distributed, but that is not true, at lease Intel IceLake Intel(R) Xeon(R) Platinum 8369B CPU @ 2.70GHz, the CPU cycle is always ODD number. This fact will result expensive ops are frequently scheduled to signle thread, which will greatly increase the RT time (in custom scenario, from ~30ms to ~45ms).

[Runtime] fix a scheduling issue

---

docs/docs_en/.readthedocs.yaml
docs/docs_zh/.readthedocs.yaml

- Add configure file: docs/docs_zh/.readthedocs.yaml docs/docs_en/.readthedocs.yaml

[Docs] Fix readthedoc build fail.
